### ISSUE TITLE
Introduction Self

### ISSUE THREAD

**Issue by Googlei** [hajirodeon/freekelasgithub#4]
Nama Saya Wilhelmus Yosta Misu,Asal Bekasi Status Masih Kuliah Smt 1 Jurusan TI di ITBU

**Comment by hajirodeon** [comment]
salam kenal jg ya...

**Comment by danyismail** [comment]
Salam kenalsaya dany dr jakarta

**Comment by hajirodeon** [comment]
sip

**Comment by ardiansyah96** [comment]
salam kenal

**Comment by hajirodeon** [comment]
salam

**Comment by alfianguide** [comment]
Mohon maap mas, bisa diclose issuenya? untuk absensi ada di issue https://github.com/hajirodeon/freekelasgithub/issues/3

**Comment by hajirodeon** [comment]
ok...
